# Generated by Django 3.1.7 on 2021-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appt_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('skype', models.CharField(default='', max_length=70)),
                ('number', models.CharField(default='', max_length=70)),
                ('date', models.CharField(default='', max_length=500)),
                ('time', models.CharField(default='', max_length=500)),
                ('subject', models.CharField(default='', max_length=500)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
