# Generated by Django 3.1.7 on 2021-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hosp_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('age', models.CharField(default='', max_length=70)),
                ('date', models.CharField(default='', max_length=70)),
                ('hospital', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
