# Generated by Django 3.1.7 on 2021-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanitization',
            fields=[
                ('sant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
